// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAspNetPrivilege = "asp_net_privileges"

// AspNetPrivilege mapped from table <asp_net_privileges>
type AspNetPrivilege struct {
	ID             int32     `gorm:"column:id;primaryKey;default:nextval('"AspNetPrivileges_Id_seq"'::regclass)" json:"id"`
	PrivilegeType  string    `gorm:"column:privilege_type" json:"privilege_type"`
	ObjID          int32     `gorm:"column:obj_id" json:"obj_id"`
	Title          string    `gorm:"column:title;not null" json:"title"`
	C              int16     `gorm:"column:c" json:"c"`
	R              int16     `gorm:"column:r" json:"r"`
	U              int16     `gorm:"column:u" json:"u"`
	D              int16     `gorm:"column:d" json:"d"`
	DateCreate     time.Time `gorm:"column:date_create" json:"date_create"`
	DateLastChange time.Time `gorm:"column:date_last_change" json:"date_last_change"`
	CreaterID      int64     `gorm:"column:creater_id" json:"creater_id"`
	ChangerID      int64     `gorm:"column:changer_id" json:"changer_id"`
}

// TableName AspNetPrivilege's table name
func (*AspNetPrivilege) TableName() string {
	return TableNameAspNetPrivilege
}
