// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAspNetRoleClaim = "AspNetRoleClaims"

// AspNetRoleClaim mapped from table <AspNetRoleClaims>
type AspNetRoleClaim struct {
	ID         int32  `gorm:"column:Id;primaryKey;default:nextval('"AspNetRoleClaims_Id_seq"'::regclass)" json:"Id"`
	RoleID     string `gorm:"column:RoleId;not null" json:"RoleId"`
	ClaimType  string `gorm:"column:ClaimType" json:"ClaimType"`
	ClaimValue string `gorm:"column:ClaimValue" json:"ClaimValue"`
}

// TableName AspNetRoleClaim's table name
func (*AspNetRoleClaim) TableName() string {
	return TableNameAspNetRoleClaim
}
