// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAspNetUserLogin = "AspNetUserLogins"

// AspNetUserLogin mapped from table <AspNetUserLogins>
type AspNetUserLogin struct {
	LoginProvider       string `gorm:"column:LoginProvider;primaryKey" json:"LoginProvider"`
	ProviderKey         string `gorm:"column:ProviderKey;primaryKey" json:"ProviderKey"`
	ProviderDisplayName string `gorm:"column:ProviderDisplayName" json:"ProviderDisplayName"`
	UserID              string `gorm:"column:UserId;not null" json:"UserId"`
}

// TableName AspNetUserLogin's table name
func (*AspNetUserLogin) TableName() string {
	return TableNameAspNetUserLogin
}
