// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAspNetRole = "AspNetRoles"

// AspNetRole mapped from table <AspNetRoles>
type AspNetRole struct {
	ID               string `gorm:"column:Id;primaryKey" json:"Id"`
	Name             string `gorm:"column:Name" json:"Name"`
	NormalizedName   string `gorm:"column:NormalizedName" json:"NormalizedName"`
	ConcurrencyStamp string `gorm:"column:ConcurrencyStamp" json:"ConcurrencyStamp"`
}

// TableName AspNetRole's table name
func (*AspNetRole) TableName() string {
	return TableNameAspNetRole
}
