// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAspNetUserClaim = "AspNetUserClaims"

// AspNetUserClaim mapped from table <AspNetUserClaims>
type AspNetUserClaim struct {
	ID         int32  `gorm:"column:Id;primaryKey;default:nextval('"AspNetUserClaims_Id_seq"'::regclass)" json:"Id"`
	UserID     string `gorm:"column:UserId;not null" json:"UserId"`
	ClaimType  string `gorm:"column:ClaimType" json:"ClaimType"`
	ClaimValue string `gorm:"column:ClaimValue" json:"ClaimValue"`
}

// TableName AspNetUserClaim's table name
func (*AspNetUserClaim) TableName() string {
	return TableNameAspNetUserClaim
}
