// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAspNetUserRole = "AspNetUserRoles"

// AspNetUserRole mapped from table <AspNetUserRoles>
type AspNetUserRole struct {
	UserID string `gorm:"column:UserId;primaryKey" json:"UserId"`
	RoleID string `gorm:"column:RoleId;primaryKey" json:"RoleId"`
}

// TableName AspNetUserRole's table name
func (*AspNetUserRole) TableName() string {
	return TableNameAspNetUserRole
}
