// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEmailTemplate = "email_templates"

// EmailTemplate mapped from table <email_templates>
type EmailTemplate struct {
	DateCreate            time.Time `gorm:"column:date_create" json:"date_create"`
	DateLastChange        time.Time `gorm:"column:date_last_change" json:"date_last_change"`
	CreaterID             int64     `gorm:"column:creater_id" json:"creater_id"`
	ChangerID             int64     `gorm:"column:changer_id" json:"changer_id"`
	KeyTc                 string    `gorm:"column:key_tc;primaryKey" json:"key_tc"`
	Subject               string    `gorm:"column:subject" json:"subject"`
	Body                  string    `gorm:"column:body" json:"body"`
	Description           string    `gorm:"column:description" json:"description"`
	StoredProcedure       string    `gorm:"column:stored_procedure" json:"stored_procedure"`
	StoredProcedureUpdate string    `gorm:"column:stored_procedure_update" json:"stored_procedure_update"`
}

// TableName EmailTemplate's table name
func (*EmailTemplate) TableName() string {
	return TableNameEmailTemplate
}
