// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEmailsSent = "emails_sent"

// EmailsSent mapped from table <emails_sent>
type EmailsSent struct {
	ID             int32     `gorm:"column:id;primaryKey;default:nextval('"EmailsSent_Id_seq"'::regclass)" json:"id"`
	DateCreate     time.Time `gorm:"column:date_create" json:"date_create"`
	DateLastChange time.Time `gorm:"column:date_last_change" json:"date_last_change"`
	CreaterID      int64     `gorm:"column:creater_id" json:"creater_id"`
	ChangerID      int64     `gorm:"column:changer_id" json:"changer_id"`
	KeyTc          string    `gorm:"column:key_tc" json:"key_tc"`
	Subject        string    `gorm:"column:subject" json:"subject"`
	Body           string    `gorm:"column:body" json:"body"`
	StudentID      int32     `gorm:"column:student_id" json:"student_id"`
	Email          string    `gorm:"column:email" json:"email"`
	Files          string    `gorm:"column:files" json:"files"`
	IsSent         bool      `gorm:"column:is_sent" json:"is_sent"`
	Message        string    `gorm:"column:message" json:"message"`
	ObjID          int32     `gorm:"column:obj_id" json:"obj_id"`
}

// TableName EmailsSent's table name
func (*EmailsSent) TableName() string {
	return TableNameEmailsSent
}
