// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLibraryStyle = "library_styles"

// LibraryStyle mapped from table <library_styles>
type LibraryStyle struct {
	ID              int32     `gorm:"column:id;primaryKey;default:nextval('"LibraryStyles_Id_seq"'::regclass)" json:"id"`
	DateCreate      time.Time `gorm:"column:date_create" json:"date_create"`
	DateLastChange  time.Time `gorm:"column:date_last_change" json:"date_last_change"`
	CreaterID       int64     `gorm:"column:creater_id" json:"creater_id"`
	ChangerID       int64     `gorm:"column:changer_id" json:"changer_id"`
	IsArchive       bool      `gorm:"column:is_archive" json:"is_archive"`
	Title           string    `gorm:"column:title" json:"title"`
	TypeStyle       string    `gorm:"column:type_style" json:"type_style"`
	Style           string    `gorm:"column:style" json:"style"`
	CategoryID      int32     `gorm:"column:category_id" json:"category_id"`
	ProjectID       int32     `gorm:"column:project_id" json:"project_id"`
	ParentID        int32     `gorm:"column:parent_id" json:"parent_id"`
	IsCategory      bool      `gorm:"column:is_category" json:"is_category"`
	TemplateStyleID int32     `gorm:"column:template_style_id" json:"template_style_id"`
}

// TableName LibraryStyle's table name
func (*LibraryStyle) TableName() string {
	return TableNameLibraryStyle
}
