// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMapSchemaTable = "map_schema_tables"

// MapSchemaTable mapped from table <map_schema_tables>
type MapSchemaTable struct {
	ID             int32     `gorm:"column:id;primaryKey;default:nextval('"MapSchemaTables_Id_seq"'::regclass)" json:"id"`
	DateCreate     time.Time `gorm:"column:date_create" json:"date_create"`
	DateLastChange time.Time `gorm:"column:date_last_change" json:"date_last_change"`
	CreaterID      int64     `gorm:"column:creater_id" json:"creater_id"`
	ChangerID      int64     `gorm:"column:changer_id" json:"changer_id"`
	Name           string    `gorm:"column:name;not null" json:"name"`
	Title          string    `gorm:"column:title" json:"title"`
	ZuluTypeID     int32     `gorm:"column:zulu_type_id" json:"zulu_type_id"`
	ZuluModeID     int32     `gorm:"column:zulu_mode_id" json:"zulu_mode_id"`
	ProjectID      int32     `gorm:"column:project_id" json:"project_id"`
	IsOneToMany    bool      `gorm:"column:is_one_to_many;not null" json:"is_one_to_many"`
	Scheme         string    `gorm:"column:scheme;not null;default:data" json:"scheme"`
	Jsonb          string    `gorm:"column:jsonb" json:"jsonb"`
}

// TableName MapSchemaTable's table name
func (*MapSchemaTable) TableName() string {
	return TableNameMapSchemaTable
}
