// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMapLayersSchemaTable = "map_layers_schema_tables"

// MapLayersSchemaTable mapped from table <map_layers_schema_tables>
type MapLayersSchemaTable struct {
	LayerID int32 `gorm:"column:layer_id;primaryKey" json:"layer_id"`
	TableID int32 `gorm:"column:table_id;primaryKey" json:"table_id"`
}

// TableName MapLayersSchemaTable's table name
func (*MapLayersSchemaTable) TableName() string {
	return TableNameMapLayersSchemaTable
}
