// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMapHandbooksList = "map_handbooks_list"

// MapHandbooksList mapped from table <map_handbooks_list>
type MapHandbooksList struct {
	ID        int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Title     string `gorm:"column:title;not null" json:"title"`
	ExtID     int32  `gorm:"column:ext_id" json:"ext_id"`
	ProjectID int32  `gorm:"column:project_id" json:"project_id"`
	CascadeID int32  `gorm:"column:cascade_id" json:"cascade_id"`
}

// TableName MapHandbooksList's table name
func (*MapHandbooksList) TableName() string {
	return TableNameMapHandbooksList
}
