// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMapLayer = "map_layers"

// MapLayer mapped from table <map_layers>
type MapLayer struct {
	ID                int32     `gorm:"column:id;primaryKey;default:nextval('"MapLayers_Id_seq"'::regclass)" json:"id"`
	DateCreate        time.Time `gorm:"column:date_create" json:"date_create"`
	DateLastChange    time.Time `gorm:"column:date_last_change" json:"date_last_change"`
	CreaterID         int64     `gorm:"column:creater_id" json:"creater_id"`
	ChangerID         int64     `gorm:"column:changer_id" json:"changer_id"`
	ProjectID         int32     `gorm:"column:project_id" json:"project_id"`
	IsArchive         bool      `gorm:"column:is_archive" json:"is_archive"`
	Title             string    `gorm:"column:title" json:"title"`
	PathLayer         string    `gorm:"column:path_layer" json:"path_layer"`
	TypeLayerID       int32     `gorm:"column:type_layer_id" json:"type_layer_id"`
	IsVisible         bool      `gorm:"column:is_visible;not null;default:true" json:"is_visible"`
	ParentID          int32     `gorm:"column:parent_id" json:"parent_id"`
	TypeGeometry      string    `gorm:"column:type_geometry" json:"type_geometry"`
	ClassName         string    `gorm:"column:class_name" json:"class_name"`
	Style             string    `gorm:"column:style" json:"style"`
	ZoomViewFrom      int16     `gorm:"column:zoom_view_from" json:"zoom_view_from"`
	ZoomViewTo        int16     `gorm:"column:zoom_view_to" json:"zoom_view_to"`
	ZuluTypeID        int32     `gorm:"column:zulu_type_id" json:"zulu_type_id"`
	ZuluModeID        int32     `gorm:"column:zulu_mode_id" json:"zulu_mode_id"`
	LibraryStyleID    int32     `gorm:"column:library_style_id" json:"library_style_id"`
	Priority          int32     `gorm:"column:priority" json:"priority"`
	VectorMinZoom     int32     `gorm:"column:vector_min_zoom" json:"vector_min_zoom"`
	VectorMaxZoom     int32     `gorm:"column:vector_max_zoom" json:"vector_max_zoom"`
	IsTileVector      bool      `gorm:"column:is_tile_vector;not null" json:"is_tile_vector"`
	ExtID             string    `gorm:"column:ext_id" json:"ext_id"`
	VectorZoomFix     int32     `gorm:"column:vector_zoom_fix" json:"vector_zoom_fix"`
	VectorZoomFixKoef float64   `gorm:"column:vector_zoom_fix_koef" json:"vector_zoom_fix_koef"`
	WmsZoomFix        int32     `gorm:"column:wms_zoom_fix" json:"wms_zoom_fix"`
	WmsCacheSec       int32     `gorm:"column:wms_cache_sec" json:"wms_cache_sec"`
	HoverStyleID      int32     `gorm:"column:hover_style_id" json:"hover_style_id"`
	TemplateLayerID   int32     `gorm:"column:template_layer_id" json:"template_layer_id"`
}

// TableName MapLayer's table name
func (*MapLayer) TableName() string {
	return TableNameMapLayer
}
