// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMapHandbook = "map_handbooks"

// MapHandbook mapped from table <map_handbooks>
type MapHandbook struct {
	ID                 int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	MapHandbooksListID int32     `gorm:"column:map_handbooks_list_id;not null" json:"map_handbooks_list_id"`
	Value              string    `gorm:"column:value;not null" json:"value"`
	Priority           int32     `gorm:"column:priority" json:"priority"`
	ParentID           int32     `gorm:"column:parent_id" json:"parent_id"`
	ExtID              int32     `gorm:"column:ext_id" json:"ext_id"`
	DateDreate         time.Time `gorm:"column:date_dreate;not null;default:now()" json:"date_dreate"`
	Jsonb              string    `gorm:"column:jsonb" json:"jsonb"`
}

// TableName MapHandbook's table name
func (*MapHandbook) TableName() string {
	return TableNameMapHandbook
}
