// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMapObject = "map_objects"

// MapObject mapped from table <map_objects>
type MapObject struct {
	ID             int64     `gorm:"column:id;primaryKey;default:nextval('"MapObjects_Id_seq"'::regclass)" json:"id"`
	ProjectID      int32     `gorm:"column:project_id" json:"project_id"`
	LayerID        int32     `gorm:"column:layer_id" json:"layer_id"`
	ZuluTypeID     int32     `gorm:"column:zulu_type_id" json:"zulu_type_id"`
	ZuluModeID     int32     `gorm:"column:zulu_mode_id" json:"zulu_mode_id"`
	Geometry       string    `gorm:"column:geometry" json:"geometry"`
	Sys            int64     `gorm:"column:sys" json:"sys"`
	Color          string    `gorm:"column:color" json:"color"`
	Angle          float64   `gorm:"column:angle" json:"angle"`
	DateCreateObj  time.Time `gorm:"column:date_create_obj" json:"date_create_obj"`
	DateDeleteObj  time.Time `gorm:"column:date_delete_obj" json:"date_delete_obj"`
	ParentID       int64     `gorm:"column:parent_id" json:"parent_id"`
	OldObjID       int64     `gorm:"column:old_obj_id" json:"old_obj_id"`
	ExtID          int64     `gorm:"column:ext_id" json:"ext_id"`
	DateLastChange time.Time `gorm:"column:date_last_change" json:"date_last_change"`
}

// TableName MapObject's table name
func (*MapObject) TableName() string {
	return TableNameMapObject
}
