// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMapProject = "map_projects"

// MapProject mapped from table <map_projects>
type MapProject struct {
	ID                     int32     `gorm:"column:id;primaryKey;default:nextval('"MapProjects_Id_seq"'::regclass)" json:"id"`
	DateCreate             time.Time `gorm:"column:date_create" json:"date_create"`
	DateLastChange         time.Time `gorm:"column:date_last_change" json:"date_last_change"`
	CreaterID              int64     `gorm:"column:creater_id" json:"creater_id"`
	ChangerID              int64     `gorm:"column:changer_id" json:"changer_id"`
	IsArchive              bool      `gorm:"column:is_archive" json:"is_archive"`
	Title                  string    `gorm:"column:title" json:"title"`
	CenterLat              float64   `gorm:"column:center_lat" json:"center_lat"`
	CenterLng              float64   `gorm:"column:center_lng" json:"center_lng"`
	DefaultZoom            int16     `gorm:"column:default_zoom" json:"default_zoom"`
	TileDefaultID          int32     `gorm:"column:tile_default_id" json:"tile_default_id"`
	CoordinateSystemID     int32     `gorm:"column:coordinate_system_id" json:"coordinate_system_id"`
	MarkerClusterGroupZoom int32     `gorm:"column:marker_cluster_group_zoom" json:"marker_cluster_group_zoom"`
	WmsProjectMapserver    string    `gorm:"column:wms_project_mapserver" json:"wms_project_mapserver"`
	ColorFilter            string    `gorm:"column:color_filter" json:"color_filter"`
	IsWmsMerge             bool      `gorm:"column:is_wms_merge;not null" json:"is_wms_merge"`
	IsWmsCache             bool      `gorm:"column:is_wms_cache;not null" json:"is_wms_cache"`
	Settings               string    `gorm:"column:settings" json:"settings"`
	Description            string    `gorm:"column:description" json:"description"`
	Image                  string    `gorm:"column:image" json:"image"`
	IsTemplate             bool      `gorm:"column:is_template;not null" json:"is_template"`
}

// TableName MapProject's table name
func (*MapProject) TableName() string {
	return TableNameMapProject
}
