// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMapSchemaColumn = "map_schema_columns"

// MapSchemaColumn mapped from table <map_schema_columns>
type MapSchemaColumn struct {
	ID             int32     `gorm:"column:id;primaryKey;default:nextval('"MapSchemaColumns_Id_seq"'::regclass)" json:"id"`
	DateCreate     time.Time `gorm:"column:date_create" json:"date_create"`
	DateLastChange time.Time `gorm:"column:date_last_change" json:"date_last_change"`
	CreaterID      int64     `gorm:"column:creater_id" json:"creater_id"`
	ChangerID      int64     `gorm:"column:changer_id" json:"changer_id"`
	TableID        int32     `gorm:"column:table_id;not null" json:"table_id"`
	Name           string    `gorm:"column:name;not null" json:"name"`
	Title          string    `gorm:"column:title" json:"title"`
	Type           string    `gorm:"column:type" json:"type"`
	IsKey          bool      `gorm:"column:is_key" json:"is_key"`
	ZuluTypeID     int32     `gorm:"column:zulu_type_id" json:"zulu_type_id"`
	ZuluModeID     int32     `gorm:"column:zulu_mode_id" json:"zulu_mode_id"`
	HandBookID     int32     `gorm:"column:hand_book_id" json:"hand_book_id"`
	ExtID          int32     `gorm:"column:ext_id" json:"ext_id"`
	CascadeID      int32     `gorm:"column:cascade_id" json:"cascade_id"`
	Priority       int32     `gorm:"column:priority" json:"priority"`
	IsView         bool      `gorm:"column:is_view;default:true" json:"is_view"`
	IsDynamic      bool      `gorm:"column:is_dynamic" json:"is_dynamic"`
}

// TableName MapSchemaColumn's table name
func (*MapSchemaColumn) TableName() string {
	return TableNameMapSchemaColumn
}
