// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSetting = "settings"

// Setting mapped from table <settings>
type Setting struct {
	DateCreate     time.Time `gorm:"column:date_create" json:"date_create"`
	DateLastChange time.Time `gorm:"column:date_last_change" json:"date_last_change"`
	CreaterID      int64     `gorm:"column:creater_id" json:"creater_id"`
	ChangerID      int64     `gorm:"column:changer_id" json:"changer_id"`
	Key            string    `gorm:"column:key;primaryKey" json:"key"`
	Title          string    `gorm:"column:title" json:"title"`
	Value          string    `gorm:"column:value" json:"value"`
}

// TableName Setting's table name
func (*Setting) TableName() string {
	return TableNameSetting
}
