// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSyncZulu = "sync_zulu"

// SyncZulu mapped from table <sync_zulu>
type SyncZulu struct {
	ID            int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ProjectID     int32     `gorm:"column:project_id" json:"project_id"`
	LayerID       int32     `gorm:"column:layer_id" json:"layer_id"`
	PathLayer     string    `gorm:"column:path_layer" json:"path_layer"`
	ZuluTypeID    int32     `gorm:"column:zulu_type_id" json:"zulu_type_id"`
	IsActive      bool      `gorm:"column:is_active;not null;default:true" json:"is_active"`
	DateNextStart time.Time `gorm:"column:date_next_start" json:"date_next_start"`
	StatusLast    string    `gorm:"column:status_last" json:"status_last"`
}

// TableName SyncZulu's table name
func (*SyncZulu) TableName() string {
	return TableNameSyncZulu
}
