// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameThemedColoring = "themed_colorings"

// ThemedColoring mapped from table <themed_colorings>
type ThemedColoring struct {
	ID             int32     `gorm:"column:id;primaryKey;default:nextval('"ThemedColorings_Id_seq"'::regclass)" json:"id"`
	DateCreate     time.Time `gorm:"column:date_create" json:"date_create"`
	DateLastChange time.Time `gorm:"column:date_last_change" json:"date_last_change"`
	CreaterID      int32     `gorm:"column:creater_id" json:"creater_id"`
	ChangerID      int32     `gorm:"column:changer_id" json:"changer_id"`
	LayerID        int32     `gorm:"column:layer_id" json:"layer_id"`
	IsArchive      bool      `gorm:"column:is_archive" json:"is_archive"`
	Title          string    `gorm:"column:title" json:"title"`
}

// TableName ThemedColoring's table name
func (*ThemedColoring) TableName() string {
	return TableNameThemedColoring
}
