// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameThemedColoringRule = "themed_coloring_rule"

// ThemedColoringRule mapped from table <themed_coloring_rule>
type ThemedColoringRule struct {
	ID               int32     `gorm:"column:id;primaryKey;default:nextval('"ThemedColoringRule_Id_seq"'::regclass)" json:"id"`
	DateCreate       time.Time `gorm:"column:date_create" json:"date_create"`
	DateLastChange   time.Time `gorm:"column:date_last_change" json:"date_last_change"`
	CreaterID        int32     `gorm:"column:creater_id" json:"creater_id"`
	ChangerID        int32     `gorm:"column:changer_id" json:"changer_id"`
	ThemedColoringID int32     `gorm:"column:themed_coloring_id" json:"themed_coloring_id"`
	LibraryStyleID   int32     `gorm:"column:library_style_id" json:"library_style_id"`
	IsArchive        bool      `gorm:"column:is_archive" json:"is_archive"`
	Title            string    `gorm:"column:title" json:"title"`
	Values           string    `gorm:"column:values" json:"values"`
}

// TableName ThemedColoringRule's table name
func (*ThemedColoringRule) TableName() string {
	return TableNameThemedColoringRule
}
