// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserInfoSetting = "user_info_settings"

// UserInfoSetting mapped from table <user_info_settings>
type UserInfoSetting struct {
	DateCreate            time.Time `gorm:"column:date_create" json:"date_create"`
	DateLastChange        time.Time `gorm:"column:date_last_change" json:"date_last_change"`
	CreaterID             int64     `gorm:"column:creater_id" json:"creater_id"`
	ChangerID             int64     `gorm:"column:changer_id" json:"changer_id"`
	ID                    int64     `gorm:"column:id;primaryKey" json:"id"`
	WbAPIKey              string    `gorm:"column:wb_api_key" json:"wb_api_key"`
	IsActiveWbAPIKey      bool      `gorm:"column:is_active_wb_api_key;not null" json:"is_active_wb_api_key"`
	TgChatID              int64     `gorm:"column:tg_chat_id" json:"tg_chat_id"`
	IsTgNotification      bool      `gorm:"column:is_tg_notification;not null" json:"is_tg_notification"`
	TgKey                 string    `gorm:"column:tg_key" json:"tg_key"`
	TgKeyOfActionDate     time.Time `gorm:"column:tg_key_of_action_date" json:"tg_key_of_action_date"`
	TgKeyCounter          int32     `gorm:"column:tg_key_counter" json:"tg_key_counter"`
	WbSuppliersLogin      string    `gorm:"column:wb_suppliers_login" json:"wb_suppliers_login"`
	WbSuppliersPassword   string    `gorm:"column:wb_suppliers_password" json:"wb_suppliers_password"`
	WbSuppliersKey        string    `gorm:"column:wb_suppliers_key" json:"wb_suppliers_key"`
	WbDateLastRequest     time.Time `gorm:"column:wb_date_last_request" json:"wb_date_last_request"`
	ExpiresWbSuppliersKey time.Time `gorm:"column:expires_wb_suppliers_key" json:"expires_wb_suppliers_key"`
}

// TableName UserInfoSetting's table name
func (*UserInfoSetting) TableName() string {
	return TableNameUserInfoSetting
}
