// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserInfoRefreshToken = "user_info_refresh_token"

// UserInfoRefreshToken mapped from table <user_info_refresh_token>
type UserInfoRefreshToken struct {
	ID              int64     `gorm:"column:id;primaryKey;default:nextval('"UserInfoRefreshToken_Id_seq"'::regclass)" json:"id"`
	UserID          int64     `gorm:"column:user_id;not null" json:"user_id"`
	DateCreate      time.Time `gorm:"column:date_create;not null" json:"date_create"`
	CreatedByIP     string    `gorm:"column:created_by_ip" json:"created_by_ip"`
	Token           string    `gorm:"column:token" json:"token"`
	Expires         time.Time `gorm:"column:expires" json:"expires"`
	RevokedDate     time.Time `gorm:"column:revoked_date" json:"revoked_date"`
	RevokedByIP     string    `gorm:"column:revoked_by_ip" json:"revoked_by_ip"`
	ReplacedByToken string    `gorm:"column:replaced_by_token" json:"replaced_by_token"`
}

// TableName UserInfoRefreshToken's table name
func (*UserInfoRefreshToken) TableName() string {
	return TableNameUserInfoRefreshToken
}
